delete from account_account where 1=1;


begin;
alter table account_account
    drop constraint account_account_parent_id_fkey;
commit;

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1, 0, 9999, 1,   current_timestamp, current_timestamp, 1, 0, 'false', 1, 'true',      'SAJIDA HOSPITAL', 0, 1, null, 'current',                 'view');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2, 1, 4999, 1,   current_timestamp, current_timestamp, 1, 1, 'false', 1, 'true',      'Balance Sheet', 1, 1, 1, 'current',                      'view');


insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3, 5000, 9998, 1, current_timestamp, current_timestamp, 1, 2, 'false', 1, 'true',     'Profit and Loss', 1, 1, 1, 'current',                    'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5001, 5001, 6000, 1, current_timestamp, current_timestamp, 1, 2, 'false', 1, 'true',     'Revenue', 1, 1, 1, 'current',                         'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6001, 6001, 7000, 1, current_timestamp, current_timestamp, 1, 2, 'false', 1, 'true',     'Direct Expense', 1, 1, 1, 'current',                  'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7001, 7001, 8000, 1, current_timestamp, current_timestamp, 1, 2, 'false', 1, 'true',     'In Direct Expense', 1, 1, 1, 'current',                  'view');



insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (4, 3, 4, 1,    current_timestamp, current_timestamp, 1, 100000, 'false', null, 12, 'true','Fixed Asset Account', 3, 1, null, null, 3, 'current',               'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (3, 2, 5, 1,    current_timestamp, current_timestamp, 1, 10, 'false', null, 12, 'true',    'Fixed Assets', 2, 1, null, null, 2, 'current',                      'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (7, 8, 9, 1,    current_timestamp, current_timestamp, 1, 110100, 'false', null, 6, 'true', 'Purchased Stocks', 4, 1, null, null, 6, 'current',                  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (8, 10, 11, 1,  current_timestamp, current_timestamp, 1, 110200, 'true', null, 2, 'true',  'Debtors', 4, 1, null, null, 6, 'current',                           'receivable');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (9, 12, 13, 1,  current_timestamp, current_timestamp, 1, 110300, 'false', null, 6, 'true', 'Tax Paid', 4, 1, null, null, 6, 'current',                          'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (31, 52, 53, 1, current_timestamp, current_timestamp, 1, 'D04', 'false', null, 9, 'true',  'UltraPoor', 4, 1, null, null, 29, 'current',                        'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (29, 49, 58, 1, current_timestamp, current_timestamp, 1, 222, 'false', null, 11, 'true',   'Discounts', 3, 1, null, null, 22, 'current',                        'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (27, 62, 63, 1, current_timestamp, current_timestamp, 1, 'D01', 'false', null, 9, 'true',  'Discount', 0, 1, null, null, null, 'current',                       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (28, 64, 65, 1, current_timestamp, current_timestamp, 1, 'D02', 'false', null, 9, 'true',  'Overcharge', 0, 1, null, null, null, 'current',                     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (25, 15, 16, 1, current_timestamp, current_timestamp, 1, 110401, 'false', null, 5, 'true', 'Cash', 5, 1, null, null, 10, 'current',                             'liquidity');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (26, 17, 18, 1, current_timestamp, current_timestamp, 1, 110402, 'false', null, 4, 'true', 'Bank', 5, 1, null, null, 10, 'current',                             'liquidity');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (10, 14, 19, 1, current_timestamp, current_timestamp, 1, 1104, 'false', null, 12, 'true',  'Bank Current Account', 4, 1, null, null, 6, 'current',              'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (11, 20, 21, 1, current_timestamp, current_timestamp, 1, 110600, 'false', null, 8, 'true', 'Opening Income Account', 4, 1, null, null, 6, 'current',            'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (6, 7, 22, 1,   current_timestamp, current_timestamp, 1, 110, 'false', null, 12, 'true',   'Current Assets', 3, 1, null, null, 5, 'current',                    'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (5, 6, 23, 1,   current_timestamp, current_timestamp, 1, 11, 'false', null, 12, 'true',    'Net Current Assets', 2, 1, null, null, 2, 'current',                'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (13, 25, 26, 1, current_timestamp, current_timestamp, 1, 120000, 'true', null, 3, 'true',  'Creditors', 3, 1, null, null, 12, 'current',                        'payable');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (14, 27, 28, 1, current_timestamp, current_timestamp, 1, 121000, 'false', null, 7, 'true', 'Tax Received', 3, 1, null, null, 12, 'current',                     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (15, 29, 30, 1, current_timestamp, current_timestamp, 1, 122000, 'true', null, 7, 'true',  'Reserve and Profit/Loss Account', 3, 1, null, null, 12, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (16, 31, 32, 1, current_timestamp, current_timestamp, 1, 123000, 'false', null, 9, 'true', 'Opening Expense Account', 3, 1, null, null, 12, 'current',          'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (12, 24, 33, 1, current_timestamp, current_timestamp, 1, 12, 'false', null, 13, 'true',    'Current Liabilities', 2, 1, null, null, 2, 'current',               'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (2, 1, 34, 1,   current_timestamp, current_timestamp, 1, 1, 'false', null, 1, 'true',      'Balance Sheet', 1, 1, null, null, 1, 'current',                     'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (19, 37, 38, 1, current_timestamp, current_timestamp, 1, 200000, 'false', null, 8, 'true', 'Product Sales', 3, 1, null, null, 18, 'current',                    'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (18, 36, 39, 1, current_timestamp, current_timestamp, 1, 20, 'false', null, 10, 'true',    'Revenue', 2, 1, null, null, 17, 'current',                          'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (21, 41, 42, 1, current_timestamp, current_timestamp, 1, 210000, 'false', null, 9, 'true', 'Cost of Goods Sold', 3, 1, null, null, 20, 'current',               'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (20, 40, 43, 1, current_timestamp, current_timestamp, 1, 21, 'false', null, 10, 'true',    'Cost of Sales', 2, 1, null, null, 17, 'current',                    'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (23, 45, 46, 1, current_timestamp, current_timestamp, 1, 220000, 'false', null, 9, 'true', 'Expenses', 3, 1, null, null, 22, 'current',                         'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (24, 47, 48, 1, current_timestamp, current_timestamp, 1, 221000, 'false', null, 9, 'true', 'Salary Expenses', 3, 1, null, null, 22, 'current',                  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (32, 54, 55, 1, current_timestamp, current_timestamp, 1, 'D05', 'false', null, 9, 'true',  'Handicapped', 4, 1, null, null, 29, 'current',                      'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (22, 44, 59, 1, current_timestamp, current_timestamp, 1, 22, 'false', null, 11, 'true',    'Overheads', 2, 1, null, null, 17, 'current',                        'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (30, 50, 51, 1, current_timestamp, current_timestamp, 1, 'D03', 'false', null, 9, 'true',  'FreedomFighters', 4, 1, null, null, 29, 'current',                  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (17, 35, 60, 1, current_timestamp, current_timestamp, 1, 2, 'false', null, 1, 'true',      'Profit and Loss', 1, 1, null, null, 1, 'current',                   'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (1, 0, 61, 1,   current_timestamp, current_timestamp, 1, 0, 'false', null, 1, 'true',      'Your Company', 0, 1, null, null, null, 'current',                   'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, currency_id, user_type, active, name, level, company_id, shortcut, note, parent_id, currency_mode, type) values (33, 56, 57, 1, current_timestamp, current_timestamp, 1, 'D06', 'false', null, 9, 'true',  'Orphan', 4, 1, null, null, 29, 'current',                           'other');









begin;
alter table account_account
    add constraint account_account_parent_id_fkey
        foreign key (parent_id)
            references account_account(id)
            on delete cascade;
commit;