delete from account_account where 1=1;


begin;
alter table account_account
    drop constraint account_account_parent_id_fkey;
commit;

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1, 0, 9999, 1,   current_timestamp, current_timestamp, 1,         9, 'false', 1, 'true',                'SAJIDA HOSPITAL', 0, 1, null, 'current',                         'view');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2, 1, 4999, 1,   current_timestamp, current_timestamp, 1,         1, 'false', 1, 'true',                'Balance Sheet', 1, 1, 1, 'current',                              'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3, 5000, 9998, 1, current_timestamp, current_timestamp, 1,        2, 'false', 1, 'true',                'Profit and Loss', 1, 1, 1, 'current',                            'view');


insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (100, 100, 1000, 1, current_timestamp, current_timestamp, 1,       11, 'false', 1, 'true',               'Non Current Assets', 1, 1, 2, 'current',                         'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (101, 101, 900, 1, current_timestamp, current_timestamp, 1,        110001, 'false', 1, 'true',           'Building', 1, 1, 100, 'current',                                 'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (102, 102, 901, 1, current_timestamp, current_timestamp, 1,        110002, 'false', 1, 'true',           'Equipments', 1, 1, 100, 'current',                               'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (103, 103, 902, 1, current_timestamp, current_timestamp, 1,        110003, 'false', 1, 'true',           'Furnitures & Fixtures', 1, 1, 100, 'current',                    'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (104, 104, 903, 1, current_timestamp, current_timestamp, 1,        110004, 'false', 1, 'true',           'Vehicles', 1, 1, 100, 'current',                                 'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1000, 1000, 2000, 1, current_timestamp, current_timestamp, 1,     12, 'false', 1, 'true',               'Current Assets', 1, 1, 2, 'current',                             'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1001, 1101, 1200, 1, current_timestamp, current_timestamp, 1,     1201, 'false', 1, 'true',             'Loan', 1, 1, 1000, 'current',                                    'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1002, 1102, 1102, 1, current_timestamp, current_timestamp, 1,     120101, 'false', 1, 'true',           'Loan To Staff', 1, 1, 1001, 'current',                           'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1003, 1103, 1103, 1, current_timestamp, current_timestamp, 1,     120102, 'false', 1, 'true',           'Loan To Staff - Motorcycle', 1, 1, 1001, 'current',              'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1100, 1100, 1300, 1, current_timestamp, current_timestamp, 1,     1202, 'false', 1, 'true',             'Advances & Prepayments', 1, 1, 1000, 'current',                  'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1101, 1101, 1201, 1, current_timestamp, current_timestamp, 1,     120201, 'false', 1, 'true',           'Advance To Employee', 1, 1, 1100, 'current',                     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1102, 1102, 1202, 1, current_timestamp, current_timestamp, 1,     120202, 'false', 1, 'true',           'Advance Office Rent', 1, 1, 1100, 'current',                     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1103, 1103, 1203, 1, current_timestamp, current_timestamp, 1,     120203, 'false', 1, 'true',           'Advance Against Salary', 1, 1, 1100, 'current',                  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1104, 1104, 1204, 1, current_timestamp, current_timestamp, 1,     120204, 'false', 1, 'true',           'Advance To Others', 1, 1, 1100, 'current',                       'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1200, 1200, 1400, 1, current_timestamp, current_timestamp, 1,     1203, 'false', 1, 'true',             'Accounts Receivables', 1, 1, 1000, 'current',                    'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1201, 1201, 1301, 1, current_timestamp, current_timestamp, 1,     120301, 'false', 1, 'true',           'Receivables from Patients', 1, 1, 1200, 'current',               'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1202, 1202, 1302, 1, current_timestamp, current_timestamp, 1,     120302, 'false', 1, 'true',           'Receivables from Machine Sales', 1, 1, 1200, 'current',          'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1203, 1203, 1303, 1, current_timestamp, current_timestamp, 1,     120303, 'false', 1, 'true',           'Other Receivables', 1, 1, 1200, 'current',                       'other');


insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1300, 1200, 1400, 1, current_timestamp, current_timestamp, 1,     1204, 'false', 1, 'true',             'Inventories', 1, 1, 1000, 'current',                             'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1301, 1201, 1301, 1, current_timestamp, current_timestamp, 1,     120401, 'false', 1, 'true',           'Optical Frame', 1, 1, 1300, 'current',                           'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1302, 1202, 1302, 1, current_timestamp, current_timestamp, 1,     120402, 'false', 1, 'true',           'Medicine', 1, 1, 1300, 'current',                                'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1400, 1400, 1600, 1, current_timestamp, current_timestamp, 1,     1205, 'false', 1, 'true',             'Cash & Bank Balance', 1, 1, 1000, 'current',                     'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1401, 1401, 1501, 1, current_timestamp, current_timestamp, 1,     120501, 'false', 1, 'true',           'Cash in Hand', 1, 1, 1400, 'current',                            'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (1402, 1402, 1502, 1, current_timestamp, current_timestamp, 1,     120502, 'false', 1, 'true',           'Cash at Bank', 1, 1, 1400, 'current',                            'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2000, 2000, 3000, 1, current_timestamp, current_timestamp, 1,     13, 'false', 1, 'true',               'Non Current Liabilities', 1, 1, 2, 'current',                    'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2001, 2001, 2900, 1, current_timestamp, current_timestamp, 1,     130101, 'false', 1, 'true',           'Capital Fund', 1, 1, 2000, 'current',                            'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2002, 2002, 2901, 1, current_timestamp, current_timestamp, 1,     130202, 'false', 1, 'true',           'Reserve', 1, 1, 2000, 'current',                                 'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2100, 2100, 2900, 1, current_timestamp, current_timestamp, 1,     1303, 'false', 1, 'true',             'Long Term Loan', 1, 1, 2000, 'current',                          'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2101, 2101, 2901, 1, current_timestamp, current_timestamp, 1,     130301, 'false', 1, 'true',           'Loan - SOF', 1, 1, 2100, 'current',                              'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2200, 2200, 2900, 1, current_timestamp, current_timestamp, 1,     1304, 'false', 1, 'true',             'Long Term Liabilities', 1, 1, 2000, 'current',                    'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2201, 2201, 2901, 1, current_timestamp, current_timestamp, 1,     130401, 'false', 1, 'true',           'Staff Security Fund', 1, 1, 2200, 'current',                     'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2300, 2300, 2900, 1, current_timestamp, current_timestamp, 1,     1305, 'false', 1, 'true',             'Accumulated Depreciation', 1, 1, 2000, 'current',                 'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2301, 2301, 2801, 1, current_timestamp, current_timestamp, 1,     130501, 'false', 1, 'true',           'Accumulated Depreciation - Furniture', 1, 1, 2300, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2302, 2302, 2802, 1, current_timestamp, current_timestamp, 1,     130502, 'false', 1, 'true',           'Accumulated Depreciation - Equipments', 1, 1, 2300, 'current',    'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (2303, 2303, 2803, 1, current_timestamp, current_timestamp, 1,     130503, 'false', 1, 'true',           'Accumulated Depreciation - Vehicles', 1, 1, 2300, 'current',      'other');


insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3000, 3000, 4000, 1, current_timestamp, current_timestamp, 1,     14, 'false', 1, 'true',               'Current Liabilities', 1, 1, 2, 'current',                         'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3100, 3100, 3900, 1, current_timestamp, current_timestamp, 1,     1401, 'false', 1, 'true',             'Inter Project Loan', 1, 1, 3000, 'current',                       'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3101, 3101, 3801, 1, current_timestamp, current_timestamp, 1,     140101, 'false', 1, 'true',           'Loan With SOF', 1, 1, 3100, 'current',                            'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3102, 3102, 3802, 1, current_timestamp, current_timestamp, 1,     140102, 'false', 1, 'true',           'Loan With MF', 1, 1, 3100, 'current',                             'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3200, 3200, 3900, 1, current_timestamp, current_timestamp, 1,     1402, 'false', 1, 'true',             'Short Term Bank Loan', 1, 1, 3000, 'current',                     'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3201, 3201, 3801, 1, current_timestamp, current_timestamp, 1,     140201, 'false', 1, 'true',           'Loan From Bank', 1, 1, 3200, 'current',                           'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3300, 3300, 3800, 1, current_timestamp, current_timestamp, 1,     1403, 'false', 1, 'true',             'Accounts Payable', 1, 1, 3000, 'current',                         'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3301, 3301, 3701, 1, current_timestamp, current_timestamp, 1,     140301, 'false', 1, 'true',           'VAT Procurement', 1, 1, 3300, 'current',                          'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3302, 3302, 3702, 1, current_timestamp, current_timestamp, 1,     140302, 'false', 1, 'true',           'Staff Income Tax', 1, 1, 3300, 'current',                         'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3303, 3303, 3703, 1, current_timestamp, current_timestamp, 1,     140303, 'false', 1, 'true',           'Office Rent Tax', 1, 1, 3300, 'current',                          'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3400, 3400, 3800, 1, current_timestamp, current_timestamp, 1,     1404, 'false', 1, 'true',             'Provisions for Expenses', 1, 1, 3000, 'current',                  'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3401, 3401, 3701, 1, current_timestamp, current_timestamp, 1,     140401, 'false', 1, 'true',           'Provisions for Salary', 1, 1, 3400, 'current',                    'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3402, 3402, 3702, 1, current_timestamp, current_timestamp, 1,     140402, 'false', 1, 'true',           'Provisions for Repair & Maintenenace', 1, 1, 3400, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (3403, 3403, 3703, 1, current_timestamp, current_timestamp, 1,     140403, 'false', 1, 'true',           'Provisions for Cleaning Materials', 1, 1, 3400, 'current',        'other');



insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5001, 5001, 6000, 1, current_timestamp, current_timestamp, 1,     21, 'false', 1, 'true',               'Revenue', 1, 1, 3, 'current',                                     'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5002, 5002, 5102, 1, current_timestamp, current_timestamp, 1,     210101, 'false', 1, 'true',           'Revenue From Obs & Gyane', 1, 1, 5001, 'current',                 'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5003, 5003, 5103, 1, current_timestamp, current_timestamp, 1,     210201, 'false', 1, 'true',           'Revenue From NICU', 1, 1, 5001, 'current',                        'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5004, 5004, 5104, 1, current_timestamp, current_timestamp, 1,     210301, 'false', 1, 'true',           'Revenue From Pediatric', 1, 1, 5001, 'current',                   'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5005, 5005, 5105, 1, current_timestamp, current_timestamp, 1,     210401, 'false', 1, 'true',           'Revenue From Dental', 1, 1, 5001, 'current',                      'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5006, 5006, 5106, 1, current_timestamp, current_timestamp, 1,     210501, 'false', 1, 'true',           'Revenue From Eye', 1, 1, 5001, 'current',                         'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5007, 5007, 5107, 1, current_timestamp, current_timestamp, 1,     210601, 'false', 1, 'true',           'Revenue From Medicine', 1, 1, 5001, 'current',                    'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5008, 5008, 5108, 1, current_timestamp, current_timestamp, 1,     210701, 'false', 1, 'true',           'Revenue From ENT', 1, 1, 5001, 'current',                         'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5009, 5009, 5109, 1, current_timestamp, current_timestamp, 1,     210801, 'false', 1, 'true',           'Revenue From Skin', 1, 1, 5001, 'current',                        'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5010, 5010, 5110, 1, current_timestamp, current_timestamp, 1,     210901, 'false', 1, 'true',           'Revenue From Orthopedic', 1, 1, 5001, 'current',                  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5011, 5011, 5111, 1, current_timestamp, current_timestamp, 1,     211001, 'false', 1, 'true',           'Revenue From Pathology', 1, 1, 5001, 'current',                   'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5012, 5012, 5112, 1, current_timestamp, current_timestamp, 1,     211101, 'false', 1, 'true',           'Revenue From Blood Bank', 1, 1, 5001, 'current',                  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5013, 5013, 5113, 1, current_timestamp, current_timestamp, 1,     211201,  'false', 1, 'true',           'Revenue From USG', 1, 1, 5001, 'current',                         'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5014, 5014, 5114, 1, current_timestamp, current_timestamp, 1,     211301, 'false', 1, 'true',           'Revenue From X-RAY', 1, 1, 5001, 'current',                       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5015, 5015, 5115, 1, current_timestamp, current_timestamp, 1,     211401, 'false', 1, 'true',           'Revenue From X-ECG', 1, 1, 5001, 'current',                       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5016, 5016, 5116, 1, current_timestamp, current_timestamp, 1,     211501, 'false', 1, 'true',           'Revenue From X-ECHO', 1, 1, 5001, 'current',                      'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5017, 5017, 5117, 1, current_timestamp, current_timestamp, 1,     211601, 'false', 1, 'true',           'Revenue From Physiotherapy', 1, 1, 5001, 'current',               'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5018, 5018, 5118, 1, current_timestamp, current_timestamp, 1,     211701, 'false', 1, 'true',           'Revenue From Emergency', 1, 1, 5001, 'current',                   'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5019, 5019, 5119, 1, current_timestamp, current_timestamp, 1,     211801, 'false', 1, 'true',           'Revenue From General Surgery', 1, 1, 5001, 'current',             'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5020, 5020, 5120, 1, current_timestamp, current_timestamp, 1,     211901, 'false', 1, 'true',           'Revenue From Ambulance Service', 1, 1, 5001, 'current',           'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5021, 5021, 5121, 1, current_timestamp, current_timestamp, 1,     212001, 'false', 1, 'true',           'Revenue From Canteen', 1, 1, 5001, 'current',                     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (5022, 5022, 5122, 1, current_timestamp, current_timestamp, 1,     212101, 'false', 1, 'true',           'Revenue From Non-Operational Activities', 1, 1, 5001, 'current',  'other');


insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6001, 6001, 7000, 1, current_timestamp, current_timestamp, 1,     22,     'false', 1, 'true',               'Direct Expense', 1, 1, 3, 'current',                               'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6101, 6101, 6201, 1, current_timestamp, current_timestamp, 1,     2201,   'false', 1, 'true',             'Salary & Benefits', 1, 1, 6001, 'current',                         'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6102, 6102, 6103, 1, current_timestamp, current_timestamp, 1,     220101, 'false', 1, 'true',           'Salary & Benefits of Obs & Gyane',    1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6103, 6103, 6104, 1, current_timestamp, current_timestamp, 1,     220102, 'false', 1, 'true',           'Salary & Benefits of NICU',           1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6104, 6104, 6105, 1, current_timestamp, current_timestamp, 1,     220103, 'false', 1, 'true',           'Salary & Benefits of Pediatric',      1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6105, 6105, 6106, 1, current_timestamp, current_timestamp, 1,     220104, 'false', 1, 'true',           'Salary & Benefits of Dental',         1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6106, 6106, 6107, 1, current_timestamp, current_timestamp, 1,     220105, 'false', 1, 'true',           'Salary & Benefits of Eye',            1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6107, 6107, 6108, 1, current_timestamp, current_timestamp, 1,     220106, 'false', 1, 'true',           'Salary & Benefits of Medicine',       1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6108, 6108, 6109, 1, current_timestamp, current_timestamp, 1,     220107, 'false', 1, 'true',           'Salary & Benefits of ENT',            1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6109, 6109, 6110, 1, current_timestamp, current_timestamp, 1,     220108, 'false', 1, 'true',           'Salary & Benefits of Skin',           1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6110, 6110, 6111, 1, current_timestamp, current_timestamp, 1,     220109, 'false', 1, 'true',           'Salary & Benefits of Orthopedic',     1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6111, 6111, 6112, 1, current_timestamp, current_timestamp, 1,     220110, 'false', 1, 'true',           'Salary & Benefits of Pathology/Lab',  1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6112, 6112, 6113, 1, current_timestamp, current_timestamp, 1,     220111, 'false', 1, 'true',           'Salary & Benefits of Blood Bank',     1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6113, 6113, 6114, 1, current_timestamp, current_timestamp, 1,     220112, 'false', 1, 'true',           'Salary & Benefits of USG',            1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6114, 6114, 6115, 1, current_timestamp, current_timestamp, 1,     220113, 'false', 1, 'true',           'Salary & Benefits of X-RAY',          1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6115, 6115, 6116, 1, current_timestamp, current_timestamp, 1,     220114, 'false', 1, 'true',           'Salary & Benefits of ECG',            1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6116, 6116, 6117, 1, current_timestamp, current_timestamp, 1,     220115, 'false', 1, 'true',           'Salary & Benefits of ECHO',           1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6117, 6117, 6118, 1, current_timestamp, current_timestamp, 1,     220116, 'false', 1, 'true',           'Salary & Benefits of Physiotherapy',  1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6118, 6118, 6119, 1, current_timestamp, current_timestamp, 1,     220117, 'false', 1, 'true',           'Salary & Benefits of Emergency',      1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6119, 6119, 6120, 1, current_timestamp, current_timestamp, 1,     220118, 'false', 1, 'true',           'Salary & Benefits of General Surgery',1, 1, 6101, 'current',       'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6120, 6120, 6121, 1, current_timestamp, current_timestamp, 1,     220119, 'false', 1, 'true',           'Salary & Benefits of Canteen',        1, 1, 6101, 'current',       'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6201, 6201, 6400, 1, current_timestamp, current_timestamp, 1,     2202, 'false', 1, 'true',             'Consultants Payment', 1, 1, 6001, 'current',                       'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6202, 6202, 6303, 1, current_timestamp, current_timestamp, 1,     220201, 'false', 1, 'true',           'Consultants Payment of Obs & Gyane',    1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6203, 6203, 6304, 1, current_timestamp, current_timestamp, 1,     220202, 'false', 1, 'true',           'Consultants Payment of NICU',           1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6204, 6204, 6305, 1, current_timestamp, current_timestamp, 1,     220203, 'false', 1, 'true',           'Consultants Payment of Pediatric',      1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6205, 6205, 6306, 1, current_timestamp, current_timestamp, 1,     220204, 'false', 1, 'true',           'Consultants Payment of Dental',         1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6206, 6206, 6307, 1, current_timestamp, current_timestamp, 1,     220205, 'false', 1, 'true',           'Consultants Payment of Eye',            1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6207, 6207, 6308, 1, current_timestamp, current_timestamp, 1,     220206, 'false', 1, 'true',           'Consultants Payment of Medicine',       1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6208, 6208, 6309, 1, current_timestamp, current_timestamp, 1,     220207, 'false', 1, 'true',           'Consultants Payment of ENT',            1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6209, 6209, 6310, 1, current_timestamp, current_timestamp, 1,     220208, 'false', 1, 'true',           'Consultants Payment of Skin',           1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6210, 6210, 6311, 1, current_timestamp, current_timestamp, 1,     220209, 'false', 1, 'true',           'Consultants Payment of Orthopedic',     1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6211, 6211, 6312, 1, current_timestamp, current_timestamp, 1,     220210, 'false', 1, 'true',           'Consultants Payment of Pathology/Lab',  1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6212, 6212, 6313, 1, current_timestamp, current_timestamp, 1,     220211, 'false', 1, 'true',           'Consultants Payment of Blood Bank',     1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6213, 6213, 6314, 1, current_timestamp, current_timestamp, 1,     220212, 'false', 1, 'true',           'Consultants Payment of USG',            1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6214, 6214, 6315, 1, current_timestamp, current_timestamp, 1,     220213, 'false', 1, 'true',           'Consultants Payment of X-RAY',          1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6215, 6215, 6316, 1, current_timestamp, current_timestamp, 1,     220214, 'false', 1, 'true',           'Consultants Payment of ECG',            1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6216, 6216, 6317, 1, current_timestamp, current_timestamp, 1,     220215, 'false', 1, 'true',           'Consultants Payment of ECHO',           1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6217, 6217, 6318, 1, current_timestamp, current_timestamp, 1,     220216, 'false', 1, 'true',           'Consultants Payment of Physiotherapy',  1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6218, 6218, 6319, 1, current_timestamp, current_timestamp, 1,     220217, 'false', 1, 'true',           'Consultants Payment of Emergency',      1, 1, 6201, 'current',     'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6219, 6219, 6320, 1, current_timestamp, current_timestamp, 1,     220218, 'false', 1, 'true',           'Consultants Payment of General Surgery',1, 1, 6201, 'current',     'other');

insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6301, 6301, 6500, 1, current_timestamp, current_timestamp, 1,     2203, 'false', 1, 'true',             'Medicine & Consumables',                    1, 1, 6001, 'current',  'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6302, 6302, 6403, 1, current_timestamp, current_timestamp, 1,     220301, 'false', 1, 'true',           'Medicine & Consumables of Obs & Gyane',     1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6303, 6303, 6404, 1, current_timestamp, current_timestamp, 1,     220302, 'false', 1, 'true',           'Medicine & Consumables of NICU',            1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6304, 6304, 6405, 1, current_timestamp, current_timestamp, 1,     220303, 'false', 1, 'true',           'Medicine & Consumables of Pediatric',       1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6305, 6305, 6406, 1, current_timestamp, current_timestamp, 1,     220304, 'false', 1, 'true',           'Medicine & Consumables of Dental',          1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6306, 6306, 6407, 1, current_timestamp, current_timestamp, 1,     220305, 'false', 1, 'true',           'Medicine & Consumables of Eye',             1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6307, 6307, 6408, 1, current_timestamp, current_timestamp, 1,     220306, 'false', 1, 'true',           'Medicine & Consumables of Medicine',        1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6308, 6308, 6409, 1, current_timestamp, current_timestamp, 1,     220307, 'false', 1, 'true',           'Medicine & Consumables of ENT',             1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6309, 6309, 6410, 1, current_timestamp, current_timestamp, 1,     220308, 'false', 1, 'true',           'Medicine & Consumables of Skin',            1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6310, 6310, 6411, 1, current_timestamp, current_timestamp, 1,     220309, 'false', 1, 'true',           'Medicine & Consumables of Orthopedic',      1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6311, 6311, 6412, 1, current_timestamp, current_timestamp, 1,     220310, 'false', 1, 'true',           'Medicine & Consumables of Pathology/Lab',   1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6312, 6312, 6413, 1, current_timestamp, current_timestamp, 1,     220311, 'false', 1, 'true',           'Medicine & Consumables of Blood Bank',      1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6313, 6313, 6414, 1, current_timestamp, current_timestamp, 1,     220312, 'false', 1, 'true',           'Medicine & Consumables of USG',             1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6314, 6314, 6415, 1, current_timestamp, current_timestamp, 1,     220313, 'false', 1, 'true',           'Medicine & Consumables of X-RAY',           1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6315, 6315, 6416, 1, current_timestamp, current_timestamp, 1,     220314, 'false', 1, 'true',           'Medicine & Consumables of ECG',             1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6316, 6316, 6417, 1, current_timestamp, current_timestamp, 1,     220315, 'false', 1, 'true',           'Medicine & Consumables of ECHO',            1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6317, 6317, 6418, 1, current_timestamp, current_timestamp, 1,     220316, 'false', 1, 'true',           'Medicine & Consumables of Physiotherapy',   1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6318, 6318, 6419, 1, current_timestamp, current_timestamp, 1,     220317, 'false', 1, 'true',           'Medicine & Consumables of Emergency',       1, 1, 6301, 'current',  'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6319, 6319, 6420, 1, current_timestamp, current_timestamp, 1,     220318, 'false', 1, 'true',           'Medicine & Consumables of General Surgery', 1, 1, 6301, 'current',  'other');


insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6400, 6401, 6500, 1, current_timestamp, current_timestamp, 1,     220401, 'false', 1, 'true',           'Cost of Food of Canteen', 1, 1, 6001, 'current',                    'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (6401, 6402, 6501, 1, current_timestamp, current_timestamp, 1,     220501, 'false', 1, 'true',           'Canteen Materials', 1, 1, 6001, 'current',                          'other');


insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7001, 7001, 8000, 1, current_timestamp, current_timestamp, 1,     23,     'false', 1, 'true',           'In Direct Expense',              1, 1, 3, 'current',                   'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7002, 7002, 7800, 1, current_timestamp, current_timestamp, 1,     2301,   'false', 1, 'true',           'Hospital Overhead',              1, 1, 7001, 'current',                'view');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7003, 7003, 7103, 1, current_timestamp, current_timestamp, 1,     230101, 'false', 1, 'true',           'Salary & Benefits',              1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7004, 7004, 7104, 1, current_timestamp, current_timestamp, 1,     230102, 'false', 1, 'true',           'Rent & Utilities',               1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7005, 7005, 7105, 1, current_timestamp, current_timestamp, 1,     230103, 'false', 1, 'true',           'Depreciation',                   1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7006, 7006, 7106, 1, current_timestamp, current_timestamp, 1,     230104, 'false', 1, 'true',           'Fuel & Lubricants',              1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7007, 7007, 7107, 1, current_timestamp, current_timestamp, 1,     230105, 'false', 1, 'true',           'Repair & Maintenance',           1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7008, 7008, 7108, 1, current_timestamp, current_timestamp, 1,     230106, 'false', 1, 'true',           'Advertising Expenses',           1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7009, 7009, 7109, 1, current_timestamp, current_timestamp, 1,     230107, 'false', 1, 'true',           'Cleaning Materials',             1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7010, 7010, 7110, 1, current_timestamp, current_timestamp, 1,     230108, 'false', 1, 'true',           'Travelling & Transportation',    1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7011, 7011, 7111, 1, current_timestamp, current_timestamp, 1,     230109, 'false', 1, 'true',           'Entertainment',                  1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7012, 7012, 7112, 1, current_timestamp, current_timestamp, 1,     230110, 'false', 1, 'true',           'Uniform, Curtain & Bedding',     1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7013, 7013, 7113, 1, current_timestamp, current_timestamp, 1,     230111, 'false', 1, 'true',           'Printing & Office Stationaries', 1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7014, 7014, 7114, 1, current_timestamp, current_timestamp, 1,     230112, 'false', 1, 'true',           'Computer Accessories',           1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7015, 7015, 7115, 1, current_timestamp, current_timestamp, 1,     230113, 'false', 1, 'true',           'Legal & Other Fees',             1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7016, 7016, 7116, 1, current_timestamp, current_timestamp, 1,     230114, 'false', 1, 'true',           'Data & Communication',           1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7017, 7017, 7117, 1, current_timestamp, current_timestamp, 1,     230115, 'false', 1, 'true',           'Medical Accessories',            1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7018, 7018, 7118, 1, current_timestamp, current_timestamp, 1,     230116, 'false', 1, 'true',           'Staff Capacity Development',     1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7019, 7019, 7119, 1, current_timestamp, current_timestamp, 1,     230117, 'false', 1, 'true',           'Other Expenses',                 1, 1, 7002, 'current',                'other');
insert into public.account_account (id, parent_left, parent_right, create_uid, create_date, write_date, write_uid, code, reconcile, user_type, active, name, level, company_id, parent_id, currency_mode, type) values (7020, 7020, 7120, 1, current_timestamp, current_timestamp, 1,     230118, 'false', 1, 'true',           'Audit & Consultancy',            1, 1, 7002, 'current',                'other');




begin;
alter table account_account
    add constraint account_account_parent_id_fkey
        foreign key (parent_id)
            references account_account(id)
            on delete cascade;
commit;