call add_user('Md. Sohel', '', 'Rana', 'M', 'Registration,Registration-App', 'sohel', 'S05127');
call add_user('Md. Tanvir', '', 'Rashid', 'M', 'Registration,Registration-App', 'tanvir', 'S05232');
call add_user('Md. Masudur', '', 'Rahman', 'M', 'Registration,Registration-App', 'masudur', 'S00392');
call add_user('Roksana Akter', '', 'Mukta', 'F', 'Registration,Registration-App', 'roksana', 'S05677');
call add_user('Md. Sagar', '', 'Hasan', 'M', 'Registration,Registration-App', 'sagar', 'T04027');
call add_user('Arefun', '', 'Nahar', 'F', 'Registration,Registration-App', 'arefun', 'T04042');
call add_user('Pampa', '', 'Saha', 'F', 'Registration,Registration-App', 'pampa', 'T04043');
call add_user('Dr. Shaikh Zulfikar', '', 'Ahmed', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_zulfikar', 'T02211');
call add_user('Dr. Mohammed Srwar', '', 'Nawaz', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_srwar', 'S05268');
call add_user('Dr. Md. Abul', '', 'Hossain', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_abul', 'S05470');
call add_user('Dr. Abu', '', 'Asma', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_asma', 'S05269');
call add_user('Dr. Afsana', '', 'Khanom', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_afsana', 'S05277');
call add_user('Dr. Md.', '', 'Shamsuzzaman', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_shamsuzzaman', 'T03190');
call add_user('Dr. Saria', '', 'Nafia', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_nafia', 'S05622');
call add_user('Dr. Md. Zahangir', '', 'Alam', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_zahangir', 'S05498');
call add_user('Dr. Dipika', '', 'Khanom', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr.dipika', 'S05516');
call add_user('Dr. Raihan Amin', '', 'Rana', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_raihan', 'S05517');
call add_user('Dr. Rumana', '', 'Islam', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr.rumana', 'S05515');
call add_user('Dr. Shirina', '', 'Akbar', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_shirina', 'S05379');
call add_user('Dr. Noor-E-', '', 'Jannat', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr.jannat', 'T02650');
call add_user('Dr. Shamim Ara', '', 'Nipa', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_nipa', 'S05496');
call add_user('Dr. Yasmin', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_yasmin', 'S04185');
call add_user('Dr. Jahanara', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_jahanara', 'S05492');
call add_user('Dr. Israt', '', 'Jahan', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_israt', 'S05493');
call add_user('Dr. Nadia', '', 'Shamsuddin', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_nadia', 'S05494');
call add_user('Dr. Sumel Rahman', '', 'Rana', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_sumel', 'S04192');
call add_user('Dr. S. M.', '', 'Saifuddin', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_saifuddin', 'S05497');
call add_user('Dr. Tahera Begum', '', 'Chisty', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_tahera', 'T03671');
call add_user('Dr. Chaity', '', 'Dev', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_chaity', 'T03672');
call add_user('Dr. Hasib Ahmed', '', 'Khan', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_hasib', 'T03672');
call add_user('Dr. Rubaiya', '', 'Sharif', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_rubaiya', 'S05519');
call add_user('Dr. Jakaria', '', 'Mostafa', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_jakaria', 'S05520');
call add_user('Dr. Md. Anowarul', '', 'Razzib', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_anowarul', 'S02367');
call add_user('Dr. Md.', '', 'Mezbahuddin', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_mezbahuddin', 'S02574');
call add_user('Dr. Mohammad', '', 'Shohel', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_shohel', 'S05616');
call add_user('Dr. Mithun Kumar', '', 'Roy', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_mithun', 'S05499');
call add_user('Dr. Ashif Mashud', '', 'Choudhury', 'M', 'Bahmni-User,Clinical-App,Doctor', 'dr_ashif', 'DEMO03');
call add_user('Dr. Kishoar Sultana', '', 'Choudhury', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_kishoar', 'DEMO04');
call add_user('Dr. Kaberi', '', 'Salam', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_kaberi', 'DEMO05');
call add_user('Dr. Afroza', '', 'Begum', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_Afroza', 'DEMO06');
call add_user('Dr. Farhana', '', 'Afroze', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_farhana', 'DEMO07');
call add_user('Dr. Afsana Haque', '', 'Chowdhury', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_afsanahaque', 'DEMO08');
call add_user('Dr. Jannatul', '', 'Ferdous', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_jannatul', 'DEMO09');
call add_user('Dr. Sajida', '', 'Nahid', 'F', 'Bahmni-User,Clinical-App,Doctor', 'dr_sajida', 'DEMO10');
call add_user('Anjana Rani', '', 'Haldar', 'F', 'Bahmni-User,Clinical-App,Doctor', 'anjana', 'T02460');
call add_user('Arefin Akter', '', 'Suki', 'F', 'Bahmni-User,Clinical-App,Doctor', 'arefin', 'T03179');
call add_user('Asrafun', '', 'Jahan', 'F', 'Bahmni-User,Clinical-App,Doctor', 'asrafun', 'S05736');
call add_user('Debi Romoni', '', 'Barman', 'F', 'Bahmni-User,Clinical-App,Doctor', 'debi', 'S00044');
call add_user('Farjana Akter', '', 'Bethi', 'F', 'Bahmni-User,Clinical-App,Doctor', 'farjana', 'T03948');
call add_user('Gita', '', 'Kirttania', 'F', 'Bahmni-User,Clinical-App,Doctor', 'gita', 'S04739');
call add_user('Hashi', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'hashi', 'T01679');
call add_user('Jasmin', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'S00536', 'S00536');
call add_user('Jui Martha', '', 'Dessi', 'F', 'Bahmni-User,Clinical-App,Doctor', 'jui', 'S05742');
call add_user('Lima', '', 'Lima', 'F', 'Bahmni-User,Clinical-App,Doctor', 'lima', 'T01877');
call add_user('Lipika Rani', '', 'Mondal', 'F', 'Bahmni-User,Clinical-App,Doctor', 'lipi', 'S03678');
call add_user('Lucy', '', 'Mondal', 'F', 'Bahmni-User,Clinical-App,Doctor', 'lucy', 'T03667');
call add_user('Mafuja', '', 'Begum', 'F', 'Bahmni-User,Clinical-App,Doctor', 'mafuja', 'T01678');
call add_user('Manika', '', 'Rani', 'F', 'Bahmni-User,Clinical-App,Doctor', 'manika', 'S03390');
call add_user('Marjan', '', 'Marjan', 'M', 'Bahmni-User,Clinical-App,Doctor', 'Marjan', 'S05231');
call add_user('Md. Ainal', '', 'Haque', 'M', 'Bahmni-User,Clinical-App,Doctor', 'ainal', 'S02263');
call add_user('Md Nazir', '', 'Ahmed', 'M', 'Bahmni-User,Clinical-App,Doctor', 'nazir', 'T03209');
call add_user('Md. Salman', '', 'Kabir', 'M', 'Bahmni-User,Clinical-App,Doctor', 'salman', 'T01715');
call add_user('Mita', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'mita', 'S04740');
call add_user('Mitali', '', 'Biswas', 'F', 'Bahmni-User,Clinical-App,Doctor', 'mitali', 'S02592');
call add_user('Mousumi', '', 'Khatun', 'F', 'Bahmni-User,Clinical-App,Doctor', 'mousumi', 'S05749');
call add_user('Mst. Lata', '', 'Khatun', 'F', 'Bahmni-User,Clinical-App,Doctor', 'lata', 'T03669');
call add_user('Mst. Lipika', '', 'Khatun', 'F', 'Bahmni-User,Clinical-App,Doctor', 'lipika', 'T03668');
call add_user('Mst.', '', 'Shila', 'F', 'Bahmni-User,Clinical-App,Doctor', 'shila', 'T01674');
call add_user('Nazma', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'nazma', 'T01878');
call add_user('Nilupa', '', 'Yesmin', 'F', 'Bahmni-User,Clinical-App,Doctor', 'nilupa', 'T03194');
call add_user('Parvin', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'parvin', 'T02869');
call add_user('Popy', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'popy', 'T03188');
call add_user('Ranjita', '', 'Baral', 'F', 'Bahmni-User,Clinical-App,Doctor', 'ranjita', 'S01782');
call add_user('Rekha', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'rekha', 'S05230');
call add_user('Repa', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'repa', 'T02889');
call add_user('Riajul', '', 'Islam', 'M', 'Bahmni-User,Clinical-App,Doctor', 'riajul', 'T03208');
call add_user('Rimla', '', 'Khatun', 'F', 'Bahmni-User,Clinical-App,Doctor', 'rimla', 'T03670');
call add_user('Rina', '', 'Dey', 'F', 'Bahmni-User,Clinical-App,Doctor', 'rina', 'S00542');
call add_user('Ritu', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'ritu', 'T03178');
call add_user('Roma', '', 'Khatun', 'F', 'Bahmni-User,Clinical-App,Doctor', 'roma', 'S05276');
call add_user('Romana', '', 'Tasmin', 'F', 'Bahmni-User,Clinical-App,Doctor', 'romana', 'S02132');
call add_user('Rozina', '', 'Khatun', 'F', 'Bahmni-User,Clinical-App,Doctor', 'rozina', 'S05233');
call add_user('Sabikun', '', 'Nahar', 'F', 'Bahmni-User,Clinical-App,Doctor', 'saba', 'T03898');
call add_user('Sahida', '', 'Khanom', 'F', 'Bahmni-User,Clinical-App,Doctor', 'sahida', 'T03576');
call add_user('Sanjida', '', 'Farzana', 'F', 'Bahmni-User,Clinical-App,Doctor', 'sanjida', 'S01627');
call add_user('Shahana', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'shahana', 'T02530');
call add_user('Shahinoor', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'shahinoor', 'S00339');
call add_user('Sharmin', '', 'Akhter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'sharmin', 'S02179');
call add_user('Sharmin Akter', '', 'Mime', 'F', 'Bahmni-User,Clinical-App,Doctor', 'mime', 'T03189');
call add_user('Shilpi', '', 'Halder', 'F', 'Bahmni-User,Clinical-App,Doctor', 'shilpi1', 'T02128');
call add_user('Shilpi Rani', '', 'Halder', 'F', 'Bahmni-User,Clinical-App,Doctor', 'shilpi', 'T02194');
call add_user('Shiuly', '', 'Adhikary', 'F', 'Bahmni-User,Clinical-App,Doctor', 'shiuly', 'S04190');
call add_user('Srabony', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'srabony', 'S02131');
call add_user('Subarna', '', 'Das', 'F', 'Bahmni-User,Clinical-App,Doctor', 'subarna', 'T01680');
call add_user('Tahmina', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'tahmina', 'T01858');
call add_user('Tamanna', '', 'Yesmin', 'F', 'Bahmni-User,Clinical-App,Doctor', 'tamanna', 'T03443');
call add_user('Umme', '', 'Salma', 'F', 'Bahmni-User,Clinical-App,Doctor', 'salma', 'T01709');
call add_user('Ms. Zinnatun', '', 'Nahar', 'F', 'Bahmni-User,Clinical-App,Doctor', 'zinnat', 'T02805');
call add_user('Alaya', '', 'Akter', 'F', 'Bahmni-User,Clinical-App,Doctor', 'alaya', 'S00732');